# Generated by Django 5.1.1 on 2024-09-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="api_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="api_client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="api_client_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="api_refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="store",
            name="api_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="inventory_software",
            field=models.CharField(
                choices=[
                    ("Excel", "Excel"),
                    ("UniCommerce", "UniCommerce"),
                    ("SAP HANA", "SAP HANA"),
                    ("LogicERP", "LogicERP"),
                ],
                default="Excel",
                max_length=255,
            ),
        ),
    ]
