# Generated by Django 5.1.1 on 2024-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0002_store_api_access_token_store_api_client_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="inventory_software",
            field=models.CharField(
                choices=[
                    ("Excel", "Excel"),
                    ("UniCommerce", "UniCommerce"),
                    ("SAP HANA", "SAP HANA"),
                    ("LogicERP", "LogicERP"),
                ],
                max_length=255,
            ),
        ),
    ]
