# Generated by Django 5.1.1 on 2024-09-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0003_alter_store_inventory_software"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="inventory_software",
            field=models.CharField(
                choices=[
                    ("excel", "Excel"),
                    ("unicommerce", "UniCommerce"),
                    ("sap_hana", "SAP HANA"),
                    ("logicerp", "LogicERP"),
                ],
                max_length=255,
            ),
        ),
    ]
