# Generated by Django 5.1.1 on 2024-09-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0004_alter_store_inventory_software"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
