# Generated by Django 5.1.1 on 2024-09-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0006_brand_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="store_images/banners/"
            ),
        ),
    ]
