# Generated by Django 5.1.1 on 2024-09-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quickcommerce", "0007_store_banner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="ckchopade23@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="chinmay chopade", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="9970303781", max_length=15),
            preserve_default=False,
        ),
    ]
